### ISSUE TITLE
config.json update

### ISSUE THREAD

**Issue by boraakoguz** [Akandesh/blazedumper#3]
client_panorama.dll has changed to client.dll please update the config file to the new version of csgo. Thanks.

**Comment by Akandesh** [comment]
I don't really need to because the dumper seems to resolve it anyways. I have updated the config on my end, it won't get pushed until there's an update though.

**Comment by Akandesh** [comment]
Nevermind, I was completely wrong. Didn't realize they didn't force a delete on the panorama dll so it was still dumping from the old dll.

**Comment by boraakoguz** [comment]
[newconfig.zip](https://github.com/Akandesh/blazedumper/files/4738262/newconfig.zip)
No problem. This config seems to dump pretty well. Just change client-panorama.dll to client.dll or use the attached one. Have a nice day!

**Comment by Akandesh** [comment]
Alright, I merged yours with mine now and re-dumped it.

**Comment by boraakoguz** [comment]
Alright that should do the trick. PS: PostProcess signature is not correct at the moment I forgot to delete that from the config. You might want to delete that too to prevent misinformation.
