### ISSUE TITLE
No autoupdate of csgo.json 2 updates miss already 

### ISSUE THREAD

**Issue by mopedchik1337** [Akandesh/blazedumper#6]
Tittle. fix pls thx https://steamdb.info/app/730/patchnotes/

**Comment by Akandesh** [comment]
You're right, VPS had restarted for some reason :-)

**Comment by mopedchik1337** [comment]
Can u put autoupdater of offsets in autorun of VPS? So offset dumper will never offline.

**Comment by Akandesh** [comment]
Good idea, I've done that now.
